"""Add deleted flag to project

Revision ID: fa3cccdc7b33
Revises: 421a04666c5b
Create Date: 2026-01-02 22:47:25.401469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3cccdc7b33'
down_revision: Union[str, Sequence[str], None] = '421a04666c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted')
    # ### end Alembic commands ###
